$:[$:.length] = 'listo/'

require 'project'
require 'uuid'

class Sln2005Generator
  def initialize
  end

  def generate(project, file_name)
    File.open(file_name, "w") do |file|
      file.puts "\xEF\xBB\xBF\n"
      file.puts 'Microsoft Visual Studio Solution File, Format Version 9.00'
      file.puts '# Visual Studio 2005'
      file.puts '# Generated by listo'

      project.projects.each do |p|
        name = p.name
        path = project.path_prefix + p.path + '/' + p.name + '.vcproj'
        path.gsub!('/', '\\')
        guid = p.guid
        file.puts "Project(\"{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}\") = \"#{name}\", \"#{path}\", \"{#{guid}}\""
        unless p.dep_projects.empty?
          file.puts '	ProjectSection(ProjectDependencies) = postProject'
          p.dep_projects.each do |dp|
            file.puts "{#{dp.guid}} = {#{dp.guid}}"
          end
          file.puts '	EndProjectSection'
        end
        file.puts 'EndProject'
      end

      file.puts 'Global'
      file.puts 'GlobalSection(SolutionConfigurationPlatforms) = preSolution'
      file.puts '        Debug|Win32 = Debug|Win32'
      file.puts '        Release|Win32 = Release|Win32'
      file.puts 'EndGlobalSection'
      file.puts 'GlobalSection(ProjectConfigurationPlatforms) = postSolution'

      project.projects.each do |p|
        guid = p.guid
        p.confs.each do |c|
          conf_name = c[0]
          file.puts "{#{guid}}.#{conf_name}|Win32.ActiveCfg = #{conf_name}|Win32"
          file.puts "{#{guid}}.#{conf_name}|Win32.Build.0 = #{conf_name}|Win32"
        end
      end
      
      file.puts 'EndGlobalSection'
      file.puts 'GlobalSection(SolutionProperties) = preSolution'
      file.puts '        HideSolutionNode = FALSE'
      file.puts 'EndGlobalSection'
      file.puts 'EndGlobal'
    end
    puts "Solution '#{project.name}' generated."
  end
end

